---
title: "scarcity_viz"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse)
```

```{r}

df1 = read.csv("base-2-normal-fixed.csv", sep = ";")
df2 = read.csv("base-2-line-patch-2-fixed.csv", sep = ";")
df3 = read.csv("base-2-random-patch-fixed.csv", sep = ";")



```

# Ok let's start with normal

```{r}

normal = ggplot(data = df1) +
  geom_smooth(mapping = aes(x = X.step., y = mean..protection..of.turtles, color = "red")) +
  geom_smooth(mapping = aes(x = X.step., y = mean..production..of.turtles, color = "blue")) +
  geom_smooth(mapping = aes(x = X.step., y = mean..predationGoods..of.turtles, color = "yellow")) +
  xlim(1000, 7000) +
  xlab("Time") +
  ylab("Effort Allocation") +
  scale_color_manual(values = c("blue", "red", "black"), labels = c("Production", "Protection", "PredationGoods")) +
  labs(title = "Environment not subjected to resource shocks")

```

```{r}

row_shocks = ggplot(data = df2) +
  geom_smooth(mapping = aes(x = X.step., y = mean..protection..of.turtles, color = "red")) +
  geom_smooth(mapping = aes(x = X.step., y = mean..production..of.turtles, color = "blue")) +
  #geom_smooth(mapping = aes(x = X.step., y = mean..predationRes..of.turtles, color = "green")) +
  geom_smooth(mapping = aes(x = X.step., y = mean..predationGoods..of.turtles, color = "yellow")) +
  xlim(1000, 7000) +
  xlab("Time") +
  ylab("Effort Allocation") +
  scale_color_manual(values = c("blue", "red", "black"), labels = c("Production", "Protection", "PredationGoods")) +
  geom_vline(xintercept = 2500) +
  geom_vline(xintercept = 5000) +
  facet_wrap(~shock.row.number) +
  labs(title = "Environment subjected to patch-row (1-5) resource shocks")

```

```{r}

random_shocks = ggplot(data = df3) +
  geom_smooth(mapping = aes(x = X.step., y = mean..protection..of.turtles, color = "red")) +
  geom_smooth(mapping = aes(x = X.step., y = mean..production..of.turtles, color = "blue")) +
  #geom_smooth(mapping = aes(x = X.step., y = mean..predationRes..of.turtles, color = "green")) +
  geom_smooth(mapping = aes(x = X.step., y = mean..predationGoods..of.turtles, color = "yellow")) +
  xlim(1000, 7000) +
  xlab("Time") +
  ylab("Effort Allocation") +
  scale_color_manual(values = c("blue", "red", "black"), labels = c("Production", "Protection", "PredationGoods")) +
  geom_vline(xintercept = 2500) +
  geom_vline(xintercept = 5000) +
  facet_wrap(~resource.shock.area) +
  labs(title = "Environment subjected to random patch (15-75) resource shocks")

```

# Combining it into one figure

```{r}

figure = ggarrange(normal, row_shocks, random_shocks,
                    labels = c("A", "B", "C"),
                    ncol = 2, nrow = 2,
                    legend = "bottom")

normal
row_shocks


```

