---
title: "soccult"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr, lme4, lmerTest)
library(tidyverse)
library(readbulk)
library(berryFunctions)

```

```{r}

df_c = read.csv("export_control.csv")
df_c2 = read.csv("export_control_2.csv")
df_c3 = read.csv("export_control_3.csv")
df_c4 = read.csv("export_control_4.csv")
df_c5 = read.csv("export_control_5.csv")

colnames(df_c5) <- c("time","prot_c","predRes_c","predGoods_c", "prod_c", "condition")

df_list <- list(df_c, df_c2, df_c3, df_c4, df_c5)

df_control = df_list %>% reduce(full_join, by='time')

df_control = df_control %>% 
  mutate(prot = (prot_c.x + prot_c.y + prot_c.x.x + prot_c.y.y + prot_c) / 5) %>% 
  mutate(predRes = (predRes_c.x + predRes_c.y + predRes_c.x.x + predRes_c.y.y + predRes_c) / 5) %>% 
  mutate(predGoods = (predGoods_c.x + predGoods_c.y + predGoods_c.x.x + predGoods_c.y.y + predGoods_c) / 5) %>% 
  mutate(prod = (prod_c.x + prod_c.y + prod_c.x.x + prod_c.y.y + prod_c) / 5)

df_control = df_control[, -c(2:25)]

# Now scarcity

df_c = read.csv("export_scarcity.csv")
df_c2 = read.csv("export_scarcity_2.csv")
df_c3 = read.csv("export_scarcity_3.csv")
df_c4 = read.csv("export_scarcity_4.csv")
df_c5 = read.csv("export_scarcity_5.csv")

colnames(df_c5) <- c("time","prot_c","predRes_c","predGoods_c", "prod_c", "condition")

df_list <- list(df_c, df_c2, df_c3, df_c4, df_c5)

df_control_scarcity = df_list %>% reduce(full_join, by='time')

df_scarcity = df_control_scarcity %>% 
  mutate(prot = (prot_c.x + prot_c.y + prot_c.x.x + prot_c.y.y + prot_c) / 5) %>% 
  mutate(predRes = (predRes_c.x + predRes_c.y + predRes_c.x.x + predRes_c.y.y + predRes_c) / 5) %>% 
  mutate(predGoods = (predGoods_c.x + predGoods_c.y + predGoods_c.x.x + predGoods_c.y.y + predGoods_c) / 5) %>% 
  mutate(prod = (prod_c.x + prod_c.y + prod_c.x.x + prod_c.y.y + prod_c) / 5)

df_scarcity = df_scarcity[, -c(2:25)]


```

```{r}
# Analysis



```

